import type { AnalyzeClosetResponse, GenerateOutfitsResponse } from "@/types/api"

export const demoAnalyzeResult: AnalyzeClosetResponse = {
  source: "manual_text",
  summary: "Parsed 5 closet items from demo data.",
  items: [
    {
      id: "demo-1",
      name: "White Oxford Shirt",
      category: "top",
      color: "white",
      material: "cotton",
      pattern: "solid",
      formality: "smart-casual",
      seasonality: ["spring", "fall"],
      tags: ["essential"],
      notes: null,
    },
    {
      id: "demo-2",
      name: "Navy Chinos",
      category: "bottom",
      color: "navy",
      material: "cotton",
      pattern: "solid",
      formality: "smart-casual",
      seasonality: ["spring", "fall"],
      tags: ["essential"],
      notes: null,
    },
    {
      id: "demo-3",
      name: "Brown Loafers",
      category: "shoes",
      color: "brown",
      material: "leather",
      pattern: "solid",
      formality: "formal",
      seasonality: ["spring", "summer", "fall"],
      tags: ["essential"],
      notes: null,
    },
    {
      id: "demo-4",
      name: "Charcoal Blazer",
      category: "outerwear",
      color: "gray",
      material: "wool-blend",
      pattern: "solid",
      formality: "formal",
      seasonality: ["fall", "winter"],
      tags: ["layer"],
      notes: null,
    },
    {
      id: "demo-5",
      name: "Silver Watch",
      category: "accessory",
      color: "gray",
      material: "stainless steel",
      pattern: "solid",
      formality: "smart-casual",
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["accent"],
      notes: null,
    },
  ],
  category_counts: {
    top: 1,
    bottom: 1,
    dress: 0,
    outerwear: 1,
    shoes: 1,
    accessory: 1,
    other: 0,
  },
  warnings: [],
}

export const demoOutfitResult: GenerateOutfitsResponse = {
  occasion: "Team offsite dinner",
  itinerary: "Office wrap-up then rooftop dinner",
  outfits: [
    {
      outfit_id: "demo-outfit-1",
      title: "Clean Smart Casual",
      pieces: [
        {
          item_id: "demo-1",
          item_name: "White Oxford Shirt",
          category: "top",
          styling_note: "Sleeves rolled for a relaxed but polished look.",
        },
        {
          item_id: "demo-2",
          item_name: "Navy Chinos",
          category: "bottom",
          styling_note: "Neutral base that supports long wear.",
        },
        {
          item_id: "demo-3",
          item_name: "Brown Loafers",
          category: "shoes",
          styling_note: "Elevates formality without sacrificing comfort.",
        },
      ],
      reasoning: "Balanced for mixed professional and social settings.",
      confidence: 0.88,
      alternatives: ["Swap loafers for white sneakers if the venue is casual."],
    },
    {
      outfit_id: "demo-outfit-2",
      title: "Layered Evening Option",
      pieces: [
        {
          item_id: "demo-1",
          item_name: "White Oxford Shirt",
          category: "top",
          styling_note: "Crisp top keeps focus on clean tailoring.",
        },
        {
          item_id: "demo-4",
          item_name: "Charcoal Blazer",
          category: "outerwear",
          styling_note: "Adds structure for evening photos and breeze.",
        },
        {
          item_id: "demo-2",
          item_name: "Navy Chinos",
          category: "bottom",
          styling_note: "Grounds the look with a darker tone.",
        },
        {
          item_id: "demo-5",
          item_name: "Silver Watch",
          category: "accessory",
          styling_note: "Subtle metallic accent for dressier moments.",
        },
      ],
      reasoning: "Best when itinerary shifts from daytime work to an evening event.",
      confidence: 0.84,
      alternatives: ["Remove blazer if the weather stays warm."],
    },
  ],
  global_tips: [
    "Pre-steam shirt and blazer to improve presentation.",
    "Carry a lint roller for quick touch-ups before dinner.",
  ],
}
